export const FETCH_CRAWLS = 'FETCH_CRAWLS';
export const FETCH_CRAWLS_SUCCESS = 'FETCH_CRAWLS_SUCCESS';
export const FETCH_CRAWLS_FAILED = 'FETCH_CRAWLS_FAILED';

export const FETCH_CRAWL = 'FETCH_CRAWL';
export const FETCH_CRAWL_SUCCESS = 'FETCH_CRAWL_SUCCESS';
export const FETCH_CRAWL_FAILED = 'FETCH_CRAWL_FAILED';
